<?php
// This file was automatically generated on Sun Dec  4 09:05:15 2016 (GMT)
// Don't modify it by hand, rather use the target lang from the Makefile.


// ../lib/GaletteFullcard/PdfFullcard.php:92 
$lang['fullcard']['Labels'] = 'Étiquettes';

// ../lib/GaletteFullcard/PdfFullcard.php:91 
$lang['fullcard']['Generated by Galette'] = 'Généré par Galette';

// ../lib/GaletteFullcard/PdfFullcard.php:75 
$lang['fullcard']['fullcard'] = 'fiche_adherent';

// ../lib/GaletteFullcard/PdfFullcard.php:249 
$lang['fullcard']['At '] = 'Fait à ';

// ../lib/GaletteFullcard/PdfFullcard.php:250 
$lang['fullcard']['On            /            /            '] = 'Le            /            /            ';

