<?php
// This file was automatically generated on Sun Nov 20 12:56:57 2016 (GMT)
// Don't modify it by hand, rather use the target lang from the Makefile.


// ../lib/GaletteFullcard/PdfFullcard.php:92 
$lang['fullcard']['Labels'] = 'Étiquettes';

// ../lib/GaletteFullcard/PdfFullcard.php:91 
$lang['fullcard']['Generated by Galette'] = 'Générer par Galette';

// ../lib/GaletteFullcard/PdfFullcard.php:75 
$lang['fullcard']['fullcard'] = 'fiche_adherent';

