<?php
// This file was automatically generated on Sun Dec  4 09:05:15 2016 (GMT)
// Don't modify it by hand, rather use the target lang from the Makefile.


// ../lib/GaletteFullcard/PdfFullcard.php:92 
$lang['fullcard']['Labels'] = 'Labels';

// ../lib/GaletteFullcard/PdfFullcard.php:91 
$lang['fullcard']['Generated by Galette'] = 'Generated by Galette';

// ../lib/GaletteFullcard/PdfFullcard.php:75 
$lang['fullcard']['fullcard'] = 'fullcard';

// ../lib/GaletteFullcard/PdfFullcard.php:249 
$lang['fullcard']['At '] = 'At ';

// ../lib/GaletteFullcard/PdfFullcard.php:250 
$lang['fullcard']['On            /            /            '] = 'On            /            /            ';

